version: '3.4'

services:
  postgres:
    container_name: online_library_instance
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: online_library_db
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: zxcv159
    volumes:
      - ./postgresql:/var/lib/postgresql/data
