# Generated by Django 4.0.2 on 2022-02-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_artists_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['genre', 'artist', 'album_name']},
        ),
    ]
