# Generated by Django 4.0.1 on 2022-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('dead_line', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Complete', 'Complete')], default='Open', max_length=11)),
            ],
        ),
    ]
