# Generated by Django 4.0.1 on 2022-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='Open', max_length=11),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Task'),
        ),
    ]
