# Generated by Django 4.0.2 on 2022-02-24 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import furniture_store.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('price', models.FloatField(validators=[furniture_store.web.validators.validate_min_price])),
                ('model', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4)])),
                ('image', models.URLField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)])),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile')),
            ],
        ),
    ]
