# Generated by Django 4.0.2 on 2022-02-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Do not show', 'Do not show'), ('Male', 'Male'), ('Female', 'Female')], default='Do not show', max_length=11, null=True),
        ),
    ]
