# Generated by Django 4.0.2 on 2022-02-11 22:13

from django.db import migrations, models
import workshop_petstagram.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[workshop_petstagram.main.validators.validate_min_date]),
        ),
    ]
